policy_name: SAPolicy
protocol: ws
host: 127.0.0.1
port: 8510
task_name: put_the_plastic_bottles_in_the_bin
env_cfg_type: yam_dual
action_type: ee
eval_batch: false
sapolicy_root: XPolicyLab/policy/SAPolicy/upstream
cfg_file: XPolicyLab/policy/SAPolicy/configs/mv51.yaml
model_path: checkpoints/finetuned/sapolicy/teleopMV51/model.ckpt
workspace: data/sapolicy/teleopMV51/model
backbone_path: checkpoints/finetuned/sapolicy/teleopMV51/backbone.pth
normalizer_path: checkpoints/finetuned/sapolicy/teleopMV51/action_normalizer.pt
output_format: action_dict
action_horizon: 50
body_frame_actions: true
tcp_forward_offset_m: 0.0
use_ema: false
ckpt_type: raw
camera_names:
- top
- left
- right
device: cuda:0
dry_run: false
checkpoint_source: sha256:49505482141081c6dd65e93ca1a4774c98a87556ad40789c6d5e5fb6a66e3011
