robot:
  group_dims:
    left_arm: 7
    right_arm: 7
  options: {}
  type: yam
command_safety: null
motion_limits:
  arm:
    max_velocity: null
    max_acceleration: null
  gripper:
    max_velocity: null
    max_acceleration: null
    max_closing_velocity: 1.0
